version: '3'
services:
  wozbot:
    build: .
    image: wozbot
    container_name: wozbot
    #restart: always
    ports:
      - "15901:5900" # VNC is port 15901 from outside
    volumes:
      - ./images/wozbot/src/config.json:/usr/src/bot/config.json
  apple2js:
    build: .
    image: apple2js
    container_name: apple2js
    #restart: always
    volumes:
      - ./images/apple2js/json/disks:/usr/src/emulator/json/disks
      - ./images/apple2js/player-standalone/cyaniide.html:/usr/src/emulator/cyaniide.html
      - ./images/apple2js/player-standalone/cyaniide.wasm:/usr/src/emulator/cyaniide.wasm
      - ./images/apple2js/player-standalone/wasm_exec.js:/usr/src/emulator/wasm_exec.js
      # - ./images/apple2js/player-standalone/dos.dsk:/usr/src/emulator/dos.dsk
      # - ./images/apple2js/disks/ugwp.dsk:/usr/src/emulator/ugwp.dsk
      - ./images/apple2js/startup.sh:/usr/src/emulator/startup.sh
