version: '3.2'
services:
  wozbot:
    image: wozbot:izapple2
    container_name: wozbot
    #restart: always
    ports:
      - "15901:5900" # VNC is port 15901 from outside
    volumes:
      - ./images/wozbot/src/config.json:/usr/src/bot/config.json
      - type: bind
        source: ./images/wozbot/startup.sh
        target: /usr/src/bot/startup.sh
      - type: bind
        source: ./images/wozbot/disks
        target: /usr/src/bot/disks
