version: '3'
services:
  wozbot:
    build: .
    image: wozbot
    container_name: wozbot
    restart: always
    volumes:
      - ./config.json:/usr/src/bot/config.json
      - ./linapple.conf:/usr/src/bot/linapple.conf
      - ./startup.sh:/usr/src/bot/startup.sh

