version: '3'
services:
  wozbot:
    build: .
    image: wozbot
    container_name: wozbot
    restart: always
    ports:
      - "15901:5900" # VNC is port 15901 from outside
    volumes:
      - ./config.json:/usr/src/bot/config.json
      - ./startup.sh:/usr/src/bot/startup.sh
      - ./disks:/usr/src/emulator/disks
